export const CLIENT_ROOMS_LABELS = {
    brandName: 'Dasher Hotel',
    unknown: {
        capacity: 'Chưa cấu hình sức chứa',
        roomType: 'Chưa gán loại phòng',
        category: 'Chưa gán danh mục',
        area: 'Chưa cập nhật',
        roomDescription: 'Chưa có mô tả cho hạng phòng này.',
    },
    index: {
        pageTitle: 'Hạng Phòng & Bảng Giá',
        heroKicker: 'Danh sách phòng',
        heroTitleSuffix: 'hạng phòng đang mở bán',
        heroDesc: 'Giá, sức chứa và tình trạng còn phòng được đồng bộ trực tiếp từ dữ liệu vận hành hiện tại.',
        filters: {
            checkIn: 'Ngày nhận',
            checkOut: 'Ngày trả',
            guests: 'Số khách',
            category: 'Danh mục',
            roomType: 'Loại phòng',
            quickSearch: 'Tìm nhanh',
            quickSearchPlaceholder: 'Tên phòng hoặc mô tả',
            allCategories: 'Tất cả danh mục',
            allRoomTypes: 'Tất cả loại phòng',
            sortPriceAsc: 'Giá tăng dần',
            sortPriceDesc: 'Giá giảm dần',
        },
        summary: {
            roomDefinitions: 'hạng phòng',
            totalRooms: 'phòng thực tế',
            resultKicker: 'Kết quả hiển thị',
            resultSuffix: 'phòng phù hợp',
            resultDesc: 'Thông tin phòng được chuẩn hóa theo loại phòng, danh mục và tồn kho hiện tại.',
        },
        empty: {
            title: 'Chưa tìm thấy phòng phù hợp.',
            desc: 'Thử đổi ngày ở hoặc bỏ bớt từ khóa tìm kiếm.',
        },
        card: {
            pricePerNight: 'Giá / đêm',
            maxGuestsSuffix: 'khách tối đa',
            noImage: 'Chưa có ảnh phòng',
            viewDetail: 'Xem chi tiết',
            soldOut: 'Hết phòng',
            unavailable: 'Hết phòng / Không khả dụng',
            availablePrefix: 'Còn',
            availableSuffix: 'phòng trống',
        },
    },
    show: {
        pageTitleSuffix: 'Chi tiết phòng',
        heroKicker: 'Chi tiết phòng',
        heroDesc: 'Thông tin loại phòng, danh mục và sức chứa được đọc trực tiếp từ cấu hình dữ liệu.',
        tags: {
            areaUnit: 'm2',
        },
        sections: {
            roomDescription: 'Mô tả phòng',
            amenitiesKicker: 'Tiện ích từ hệ thống',
            amenitiesTitle: 'Các tiện ích đi kèm',
            relatedKicker: 'Gợi ý thêm',
            relatedTitle: 'Phòng cùng danh mục',
            bookingKicker: 'Đặt phòng',
            bookingPerNight: '/ đêm',
        },
        labels: {
            backToList: 'Quay lại danh sách',
            roomType: 'Loại phòng',
            category: 'Danh mục',
            capacity: 'Sức chứa',
            area: 'Diện tích',
            basePrice: 'Giá gốc',
            checkIn: 'Ngày nhận phòng',
            checkOut: 'Ngày trả phòng',
            guests: 'Số lượng khách',
            capacityHintPrefix: 'Sức chứa loại phòng:',
            totalText: 'TỔNG CỘNG',
            noAmenities: 'Phòng này chưa gắn tiện ích trong hệ thống.',
            noImage: 'Chưa có ảnh phòng',
            proceed: 'Tiến hành đặt phòng',
            temporarySoldOut: 'Tạm hết phòng',
            roomCountPrefix: 'Hiện có',
            roomCountSuffix: 'phòng thực tế thuộc hạng này.',
            relatedSoldOut: 'Hết phòng',
        },
        status: {
            bookablePrefix: 'Có thể đặt ngay',
            bookableSuffix: 'phòng trống',
            unbookable: 'Hạng phòng này đang hết phòng, chưa thể đặt.',
            availabilityPrefix: 'Còn',
            availabilitySuffix: 'phòng trống theo ngày bạn chọn.',
            unavailableByDate: 'Hiện không còn phòng trống theo ngày bạn chọn.',
        },
        pricing: {
            nightsSuffix: 'đêm',
            multiplySign: 'x',
        },
        fallbackDescription: 'Chưa có mô tả cho hạng phòng này.',
    },
    validation: {
        noAvailability: 'Hạng phòng này hiện không còn phòng trống. Vui lòng chọn hạng phòng khác.',
        invalidDates: 'Vui lòng chọn ngày nhận và trả phòng hợp lệ.',
        guestsExceededPrefix: 'Số khách vượt sức chứa của loại phòng này. Tối đa',
        guestsExceededSuffix: 'khách.',
    },
};