<?php

return [
    'landing_pages' => [
        'dashboard.view' => 'dashboard',
        'booking.view' => 'admin.bookings.index',
        'customer.view' => 'admin.customers.index',
        'contact_requests.view' => 'admin.contact-requests.index',
        'invoice.view' => 'admin.invoices.index',
        'rooms.manage' => 'admin.rooms.index',
        'staff.view' => 'admin.staffs.index',
        'staff.manage' => 'admin.users.index',
        'roles.manage' => 'admin.roles.index',
    ],

    'route_permissions' => [
        'dashboard' => 'dashboard.view',

        'admin.bookings.index' => 'booking.view',
        'admin.bookings.history' => 'booking.view',
        'admin.bookings.show' => 'booking.view',
        'admin.bookings.search-customers' => 'booking.view',
        'admin.bookings.create' => 'booking.create',
        'admin.bookings.store' => 'booking.create',
        'admin.bookings.quick-customer' => 'booking.create',
        'admin.bookings.update' => 'booking.update',
        'admin.bookings.update-status' => 'booking.update',
        'admin.bookings.add-service' => 'booking.update',
        'admin.bookings.api-rooms' => 'booking.update',
        'admin.bookings.deposit' => 'booking.update',
        'admin.bookings.check-in' => 'booking.checkin_checkout',
        'admin.bookings.check-out' => 'booking.checkin_checkout',
        'admin.bookings.cancel' => 'booking.cancel',
        'admin.bookings.pay' => 'invoice.pay',

        'admin.customers.index' => 'customer.view',
        'admin.customers.history' => 'customer.view',
        'admin.customers.show' => 'customer.view',
        'admin.customers.create' => 'customer.create',
        'admin.customers.store' => 'customer.create',
        'admin.customers.edit' => 'customer.update',
        'admin.customers.update' => 'customer.update',
        'admin.customers.destroy' => 'customer.delete',

        'admin.invoices.index' => 'invoice.view',
        'admin.invoices.show' => 'invoice.view',
        'admin.invoices.export' => 'invoice.view',
        'admin.invoices.generate' => 'invoice.generate',
        'admin.invoices.pay' => 'invoice.pay',

        'admin.staffs.index' => 'staff.view',
        'admin.staffs.show' => 'staff.view',
        'admin.staffs.create' => 'staff.manage',
        'admin.staffs.store' => 'staff.manage',
        'admin.staffs.edit' => 'staff.manage',
        'admin.staffs.update' => 'staff.manage',
        'admin.staffs.destroy' => 'staff.manage',

        'admin.roles.index' => 'roles.manage',
        'admin.roles.create' => 'roles.manage',
        'admin.roles.store' => 'roles.manage',
        'admin.roles.show' => 'roles.manage',
        'admin.roles.edit' => 'roles.manage',
        'admin.roles.update' => 'roles.manage',
        'admin.roles.destroy' => 'roles.manage',

        'admin.rooms.index' => 'rooms.manage',
        'admin.rooms.create' => 'rooms.manage',
        'admin.rooms.store' => 'rooms.manage',
        'admin.rooms.show' => 'rooms.manage',
        'admin.rooms.edit' => 'rooms.manage',
        'admin.rooms.update' => 'rooms.manage',
        'admin.rooms.destroy' => 'rooms.manage',
        'admin.room-definitions.index' => 'rooms.manage',
        'admin.room-definitions.create' => 'rooms.manage',
        'admin.room-definitions.store' => 'rooms.manage',
        'admin.room-definitions.show' => 'rooms.manage',
        'admin.room-definitions.edit' => 'rooms.manage',
        'admin.room-definitions.update' => 'rooms.manage',
        'admin.room-definitions.destroy' => 'rooms.manage',
        'admin.room-types.index' => 'rooms.manage',
        'admin.room-types.create' => 'rooms.manage',
        'admin.room-types.store' => 'rooms.manage',
        'admin.room-types.show' => 'rooms.manage',
        'admin.room-types.edit' => 'rooms.manage',
        'admin.room-types.update' => 'rooms.manage',
        'admin.room-types.destroy' => 'rooms.manage',
        'admin.room-categories.index' => 'rooms.manage',
        'admin.room-categories.create' => 'rooms.manage',
        'admin.room-categories.store' => 'rooms.manage',
        'admin.room-categories.show' => 'rooms.manage',
        'admin.room-categories.edit' => 'rooms.manage',
        'admin.room-categories.update' => 'rooms.manage',
        'admin.room-categories.destroy' => 'rooms.manage',
        'admin.amenities.index' => 'rooms.manage',
        'admin.amenities.create' => 'rooms.manage',
        'admin.amenities.store' => 'rooms.manage',
        'admin.amenities.show' => 'rooms.manage',
        'admin.amenities.edit' => 'rooms.manage',
        'admin.amenities.update' => 'rooms.manage',
        'admin.amenities.destroy' => 'rooms.manage',
        'admin.services.index' => 'rooms.manage',
        'admin.services.create' => 'rooms.manage',
        'admin.services.store' => 'rooms.manage',
        'admin.services.show' => 'rooms.manage',
        'admin.services.edit' => 'rooms.manage',
        'admin.services.update' => 'rooms.manage',
        'admin.services.destroy' => 'rooms.manage',

        'admin.users.index' => 'staff.manage',
        'admin.users.create' => 'staff.manage',
        'admin.users.store' => 'staff.manage',
        'admin.users.show' => 'staff.manage',
        'admin.users.edit' => 'staff.manage',
        'admin.users.update' => 'staff.manage',
        'admin.users.destroy' => 'staff.manage',

        'admin.backups.index' => 'roles.manage',
        'admin.backups.create' => 'roles.manage',
        'admin.backups.download' => 'roles.manage',
        'admin.backups.destroy' => 'roles.manage',

        'admin.contact-requests.index' => 'contact_requests.view',
        'admin.contact-requests.update-status' => 'contact_requests.update',
    ],
];
